config/routes.rb
Rails.application.routes.draw do

  root to: 'login#index'
  post '/', to: 'login#index'
  get 'logout', to: 'login#logout'
  resources :users
  get 'proverbs', to: 'proverbs#import'

end

app/models/proverb.rb
class Proverb < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :password
  before_validation :sha256, only:[:password]

  private
    def sha256
      self.salt = srand.to_s
      self.password = Digest::SHA256.hexdigest("#{self.salt}#{self.password}")
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :login
  def login
    if User.any?
      if User.find_by_id(session[:current_user])
      else
        redirect_to root_path
      end
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_filter :login
  def index
    @user=User.find_by_name(params[:name])
    if @user
      @password=Digest::SHA256.hexdigest("#{@user.salt}#{params[:password]}")
      if @password==@user.password
        session[:current_user]=@user.id
      end
    end
  end

  def logout
    session[:current_user]=nil
    redirect_to root_path
  end

end

app/controllers/proverbs_controller.rb
class ProverbsController < ApplicationController
  before_action :set_proverb, only: [:show, :edit, :update, :destroy]

  # GET /proverbs
  # GET /proverbs.json
#  def index
#    @proverbs = Proverb.all
#  end

  # GET /proverbs/1
  # GET /proverbs/1.json
#  def show
#  end

  # GET /proverbs/new
#  def new
#    @proverb = Proverb.new
#  end

  # GET /proverbs/1/edit
#  def edit
#  end

  # POST /proverbs
  # POST /proverbs.json
  def create
    @proverb = Proverb.new(proverb_params)

#    respond_to do |format|
#      if @proverb.save
#        format.html { redirect_to @proverb, notice: 'Proverb was successfully created.' }
#        format.json { render :show, status: :created, location: @proverb }
#      else
#        format.html { render :new }
#        format.json { render json: @proverb.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PATCH/PUT /proverbs/1
  # PATCH/PUT /proverbs/1.json
#  def update
#    respond_to do |format|
#      if @proverb.update(proverb_params)
#        format.html { redirect_to @proverb, notice: 'Proverb was successfully updated.' }
#        format.json { render :show, status: :ok, location: @proverb }
#      else
#        format.html { render :edit }
#        format.json { render json: @proverb.errors, status: :unprocessable_entity }
#      end
#    end
    def import
      @proverbs=Proverb.all
      @proverbs.each do |proverb|
        proverb.destroy
      end
      @imports=SmarterCSV.process('quotes.csv')
      @imports.each do |proverb|
        Proverb.create(proverb)
      end
      redirect_to root_path, notice: 'Proverbs imported.'
    end

  # DELETE /proverbs/1
  # DELETE /proverbs/1.json
  def destroy
    @proverb.destroy
#    respond_to do |format|
#      format.html { redirect_to proverbs_url, notice: 'Proverb was successfully destroyed.' }
#      format.json { head :no_content }
#    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proverb
      @proverb = Proverb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proverb_params
      params.require(:proverb).permit(:quote, :author)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/proverbs_helper.rb
module ProverbsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ins3cure" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Ins3cure</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if session[:current_user] %>
              <li><%= link_to "Logged in as #{User.find_by_id(session[:current_user]).name}", "/path1" %></li>
              <li><%= link_to "Manage Users", "/users"  %></li>
              <li><%= link_to "Logout", "/logout"  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
<% if Proverb.any? %>
  <blockquote><p>
    <% proverb=Proverb.all[srand % Proverb.all.length] %>
    <%=proverb.quote %>
  <footer><%=proverb.author %></footer>
  </p></blockquote>
<% end %>
      <footer>
        <p>&copy; Fdisk 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/login/_form.html.erb
<%= form_tag root_path do %>

  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/login/index.html.erb
<img src="/ins3cure.png">
<h1>Login</h1>
<%= render 'form' %>

app/views/proverbs/_form.html.erb
<%= form_for(@proverb) do |f| %>
  <% if @proverb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proverb.errors.count, "error") %> prohibited this proverb from being saved:</h2>

      <ul>
      <% @proverb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_field :quote %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proverbs/edit.html.erb
<h1>Editing proverb</h1>

<%= render 'form' %>

<%= link_to 'Show', @proverb %> |
<%= link_to 'Back', proverbs_path %>

app/views/proverbs/index.html.erb
<h1>Listing proverbs</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proverbs.each do |proverb| %>
      <tr>
        <td><%= proverb.quote %></td>
        <td><%= proverb.author %></td>
        <td><%= link_to 'Show', proverb %></td>
        <td><%= link_to 'Edit', edit_proverb_path(proverb) %></td>
        <td><%= link_to 'Destroy', proverb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proverb', new_proverb_path %>

app/views/proverbs/new.html.erb
<h1>New proverb</h1>

<%= render 'form' %>

<%= link_to 'Back', proverbs_path %>

app/views/proverbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @proverb.quote %>
</p>

<p>
  <strong>Author:</strong>
  <%= @proverb.author %>
</p>

<%= link_to 'Edit', edit_proverb_path(@proverb) %> |
<%= link_to 'Back', proverbs_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Save User', class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Add/Edit Users</h1>

<%= link_to 'New User' , new_user_path, class: "btn btn-warning" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Change name/Reset Password', edit_user_path(user), class: "badge" %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "badge fa fa-trash-o" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>